name = "diary-app"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "DIARY_KV"
id = "11eb7cdef6914b4f8af8f2a21b251ded"
